name: Build static website

on:
  workflow_dispatch:
  push: { branches: [ "master", "main" ] }


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run compiler
        run: make build

      - name: setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull

      - name: commit changes
        run: |
          git add .
          git commit -m ":sparkles: Updated Website" || echo "No changes to commit"
          git push || echo "No changes to push"
